package util;


import contract.TemplateFormat;

/**
 * Converts generated document bytes between output formats.
 */
public interface DocumentFormatConverter {

    /**
     * Converts generated bytes from source format into target format.
     *
     * @param sourceBytes  generated bytes in source format
     * @param sourceFormat source format
     * @param targetFormat requested target format
     * @return converted bytes
     */
    byte[] convert(byte[] sourceBytes, TemplateFormat sourceFormat, TemplateFormat targetFormat);
}
