package io.github.ogbozoyan.util;

import io.github.ogbozoyan.contract.TemplateFormat;
import io.github.ogbozoyan.exception.TemplateReadWriteException;
import lombok.extern.slf4j.Slf4j;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.Comparator;
import java.util.List;
import java.util.Locale;
import java.util.concurrent.TimeUnit;
import java.util.stream.Stream;

/**
 * Converts documents via LibreOffice/soffice in headless mode.
 *
 * <p>Used only for post-convert output routes:
 * {@code XLS/XLSX -> ODS} and {@code DOC/DOCX -> ODT}.
 */
@Slf4j
public class LibreOfficeDocumentFormatConverter implements DocumentFormatConverter {

    private static final List<String> OFFICE_BINARIES = List.of("soffice", "libreoffice");
    private static final long CONVERT_TIMEOUT_SECONDS = 60L;

    /**
     * Converts generated bytes using external LibreOffice process.
     *
     * @param sourceBytes  source bytes
     * @param sourceFormat source format
     * @param targetFormat target format
     * @return converted bytes
     * @throws TemplateReadWriteException when conversion fails, times out, or office binary is unavailable
     */
    @Override
    public byte[] convert(byte[] sourceBytes, TemplateFormat sourceFormat, TemplateFormat targetFormat) {
        log.trace("convert() - start: sourceFormat={}, targetFormat={}, sourceBytesLength={}",
            sourceFormat, targetFormat, sourceBytes == null ? null : sourceBytes.length);
        if (sourceFormat == targetFormat) {
            log.trace("convert() - end: converted=false, reason=sameFormat, outputBytesLength={}",
                sourceBytes == null ? null : sourceBytes.length);
            return sourceBytes;
        }

        String binary = resolveOfficeBinary();
        String targetExtension = targetFormat.extension().substring(1).toLowerCase(Locale.ROOT);

        Path workDir = null;
        try {
            workDir = Files.createTempDirectory("reportgen-convert-");
            Path inputFile = workDir.resolve("generated" + sourceFormat.extension());
            Files.write(inputFile, sourceBytes);

            List<String> command = List.of(
                binary,
                "--headless",
                "--convert-to",
                targetExtension,
                "--outdir",
                workDir.toString(),
                inputFile.toString()
            );

            log.trace("convert() - command: sourceFormat={}, targetFormat={}, binary={}", sourceFormat, targetFormat, binary);
            Process process = new ProcessBuilder(command)
                .redirectErrorStream(true)
                .start();

            boolean finished = process.waitFor(CONVERT_TIMEOUT_SECONDS, TimeUnit.SECONDS);
            String processOutput = new String(process.getInputStream().readAllBytes(), StandardCharsets.UTF_8);

            if (!finished) {
                process.destroyForcibly();
                throw new TemplateReadWriteException("LibreOffice conversion timed out: " + sourceFormat + " -> " + targetFormat);
            }

            if (process.exitValue() != 0) {
                throw new TemplateReadWriteException(
                    "LibreOffice conversion failed (" + process.exitValue() + "): " + processOutput
                );
            }

            Path outputFile = workDir.resolve("generated." + targetExtension);
            if (!Files.exists(outputFile)) {
                throw new TemplateReadWriteException(
                    "LibreOffice did not produce output file for " + sourceFormat + " -> " + targetFormat
                );
            }

            byte[] converted = Files.readAllBytes(outputFile);
            log.trace("convert() - end: converted=true, outputBytesLength={}", converted.length);
            return converted;
        } catch (IOException e) {
            log.error("convert() - end with error: ioFailure=true", e);
            throw new TemplateReadWriteException("Failed to execute LibreOffice conversion", e);
        } catch (InterruptedException e) {
            Thread.currentThread().interrupt();
            log.error("convert() - end with error: interrupted=true", e);
            throw new TemplateReadWriteException("LibreOffice conversion interrupted", e);
        } finally {
            if (workDir != null) {
                deleteRecursively(workDir);
            }
        }
    }

    /**
     * Resolves first available office binary from known candidates.
     *
     * @return binary executable name
     * @throws TemplateReadWriteException when no candidate is available in PATH
     */
    private String resolveOfficeBinary() {
        log.trace("resolveOfficeBinary() - start: candidates={}", OFFICE_BINARIES);
        for (String candidate : OFFICE_BINARIES) {
            try {
                Process process = new ProcessBuilder(candidate, "--version")
                    .redirectErrorStream(true)
                    .start();
                if (process.waitFor(5, TimeUnit.SECONDS) && process.exitValue() == 0) {
                    log.trace("resolveOfficeBinary() - end: binary={}", candidate);
                    return candidate;
                }
            } catch (Exception ignored) {
                log.warn("resolveOfficeBinary() - warning: candidateUnavailable={}", candidate);
            }
        }
        log.error("resolveOfficeBinary() - end with error: binaryNotFound=true");
        throw new TemplateReadWriteException(
            "LibreOffice is required for ODS/ODT export. Install 'soffice' or 'libreoffice' and add it to PATH."
        );
    }

    /**
     * Deletes temporary conversion directory recursively.
     *
     * @param root temporary root directory
     */
    private void deleteRecursively(Path root) {
        log.trace("deleteRecursively() - start: root={}", root);
        try (Stream<Path> stream = Files.walk(root)) {
            stream.sorted(Comparator.reverseOrder())
                .forEach(path -> {
                    try {
                        Files.deleteIfExists(path);
                    } catch (IOException ignored) {
                        log.warn("deleteRecursively() - warning: failedToDeletePath={}", path);
                    }
                });
        } catch (IOException ignored) {
            log.warn("deleteRecursively() - warning: failedToWalkRoot={}", root);
        }
        log.trace("deleteRecursively() - end: root={}", root);
    }
}
