package io.github.ogbozoyan.util;


import io.github.ogbozoyan.contract.GeneratedReport;
import io.github.ogbozoyan.contract.TemplateFormat;
import io.github.ogbozoyan.contract.TemplateInput;
import lombok.experimental.UtilityClass;
import lombok.extern.slf4j.Slf4j;
import org.apache.commons.lang3.StringUtils;

/**
 * Serializes generation result with normalized filename and content type.
 */
@UtilityClass
@Slf4j
public class ReportSerializer {

    /**
     * Builds final generated report with normalized metadata.
     *
     * <p>File name extension is rewritten to match target format.
     *
     * @param input            source template input
     * @param format           final output format
     * @param bytes            generated bytes
     * @param warningCollector warning collector
     * @return generated report object
     */
    public static GeneratedReport serialize(
        TemplateInput input,
        TemplateFormat format,
        byte[] bytes,
        WarningCollector warningCollector
    ) {
        log.info("serialize() - start: inputFileName={}, format={}, bytesLength={}, warnings={}",
            input == null ? null : input.fileName(),
            format,
            bytes == null ? null : bytes.length,
            warningCollector == null ? null : warningCollector.asList().size());
        String fileName = normalizeFileName(input.fileName(), format);
        String contentType = format.contentType();
        GeneratedReport report = new GeneratedReport(fileName, contentType, bytes, warningCollector.asList());
        log.info("serialize() - end: outputFileName={}, contentType={}, warnings={}",
            report.fileName(), report.contentType(), report.warnings().size());
        return report;
    }

    /**
     * Normalizes output file name to target format extension.
     *
     * @param fileName requested file name
     * @param format   output format
     * @return normalized file name
     */
    private static String normalizeFileName(String fileName, TemplateFormat format) {
        if (StringUtils.isEmpty(fileName)) {
            return "generated" + format.extension();
        }

        String lower = fileName.toLowerCase();
        if (lower.endsWith(".xls")
            || lower.endsWith(".xlsx")
            || lower.endsWith(".ods")
            || lower.endsWith(".doc")
            || lower.endsWith(".docx")
            || lower.endsWith(".odt")
            || lower.endsWith(".pdf")) {
            return replaceExtension(fileName, format.extension());
        }

        return fileName + format.extension();
    }

    /**
     * Replaces current extension with target extension.
     *
     * @param fileName  file name
     * @param extension target extension with leading dot
     * @return file name with replaced extension
     */
    private static String replaceExtension(String fileName, String extension) {
        int dot = fileName.lastIndexOf('.');
        if (dot < 0) {
            return fileName + extension;
        }
        return fileName.substring(0, dot) + extension;
    }
}
